name: 'アプリケーションビルド & リリース'

on:
  push:
    # タグがpushされたときのみ実行
    tags:
      - 'v*'
  # 手動実行も可能に
  workflow_dispatch:

# GitHubトークンに必要な権限を付与
permissions:
  contents: write
  packages: read

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: ソースコードのチェックアウト
        uses: actions/checkout@v3

      - name: NodeJSセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Rustセットアップ
        uses: dtolnay/rust-toolchain@stable

      - name: Rustキャッシュ
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # 依存関係のインストール
      - name: 依存関係インストール
        run: npm ci

      # ビルド
      - name: Tauriビルド
        id: tauri-build
        uses: tauri-apps/tauri-action@v0.5.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Lucentia ${{ github.ref_name }}'
          releaseBody: |
            # Lucentia ${{ github.ref_name }}
            
            ## 主な機能
            
            - **動画ダウンロード**：YouTubeやbilibili動画をダウンロード可能
            - **自動ファイル名生成**：動画タイトルを自動検出
            - **ダウンロード進捗表示**：リアルタイムの進捗バー
            - **yt-dlp自動ダウンロード**：内部で自動的にyt-dlpをセットアップ
            - **bilibili対応**：自動的にブラウザからcookieを取得
            
            ## インストール方法
            
            1. お使いのプラットフォームに合わせたインストーラーをダウンロード：
              - Windows: `.msi`ファイル
              - macOS: `.dmg`ファイル
            
            2. インストーラーを実行してインストールを完了
          releaseDraft: true
          prerelease: false
          # Windowsでマイクロソフト証明書を使用する場合は以下をアンコメント
          # windowsCodeSigningPfxBase64: ${{ secrets.WINDOWS_PFX_BASE64 }}
          # windowsCodeSigningPfxPassword: ${{ secrets.WINDOWS_PFX_PASSWORD }}
          # macOSでApple証明書を使用する場合は以下をアンコメント
          # macOsCertificateBase64: ${{ secrets.MACOS_CERTIFICATE_BASE64 }}
          # macOsCertificatePassword: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
          # macOsSigningIdentity: ${{ secrets.MACOS_SIGNING_IDENTITY }}
          # アップデーター用のキーを設定する場合は以下をアンコメント
          # tauriPrivateKeyBase64: ${{ secrets.TAURI_PRIVATE_KEY }}
          # tauriPrivateKeyPassword: ${{ secrets.TAURI_KEY_PASSWORD }} 