name: 'テストビルド'

on:
  pull_request:
    branches: [main]

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: ソースコードのチェックアウト
        uses: actions/checkout@v4

      - name: Node.jsセットアップ
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Rustセットアップ
        uses: dtolnay/rust-toolchain@stable

      - name: Rustキャッシュ
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: 依存関係インストール
        run: npm ci

      - name: Tauriビルドテスト
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
