name: 'テストビルド'

on:
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: ソースコードのチェックアウト
        uses: actions/checkout@v3

      - name: NodeJSセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Rustセットアップ
        uses: dtolnay/rust-toolchain@stable

      - name: Rustキャッシュ
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # LinuxビルドのためにWebkitGTKをインストール
      - name: LinuxビルドツールインストールとWebKitGTKインストール
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          sudo apt-get install -y libglib2.0-dev glib-networking libsoup2.4-dev
          sudo apt-get install -y pkg-config
          # 念のためpkg-configパスを設定
          echo "PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      # 依存関係のインストール
      - name: 依存関係インストール
        run: npm ci

      # ビルドをテスト
      - name: Tauriビルドテスト
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 